from bot.conversations.add_stats import ADD_STATS_HANDLERS
from bot.conversations.battle import BATTLE_HANDLER
from bot.conversations.chat_xp import CHAT_XP_HANDLER
from bot.conversations.config_group import CONFIG_GROUP_HANDLERS
from bot.conversations.config_player import CONFIG_PLAYER_HANDLERS
from bot.conversations.create_char import CREATE_CHAR_HANDLER
from bot.conversations.help import HELP_HANDLERS
from bot.conversations.sign_up_group import SIGNUP_GROUP_HANDLER
from bot.conversations.sign_up_player import SIGNUP_PLAYER_HANDLER
from bot.conversations.view_group import VIEW_GROUP_HANDLERS
from bot.conversations.view_player import VIEW_PLAYER_HANDLERS
from bot.conversations.view_char import VIEW_CHAR_HANDLERS
from bot.conversations.rest import REST_HANDLERS
from bot.conversations.item import TREASURE_HANDLERS
from bot.conversations.bag import BAG_HANDLER, DROP_HANDLERS
from bot.conversations.equips import VIEW_EQUIPS_HANDLERS
from bot.conversations.debug import DEBUG_HANDLERS
from bot.conversations.close import CLOSE_MSG_HANDLER
from bot.conversations.race import RACES_HANDLERS
from bot.conversations.classe import CLASSES_HANDLERS
