# COMMANDS
from rpgram.enums import EmojiEnum


COMMANDS = ['duelo', 'duel']
CANCEL_COMMANDS = [
    'cancelar_batalha',
    'cancelar_duelo',
    'cancel_battle',
    'cancel_duel'
]

# CALLBACK DATA
# ENTER IN BATTLE
CALLBACK_ENTER_BLUE_TEAM = 'blue'
CALLBACK_ENTER_RED_TEAM = 'red'
CALLBACK_START_BATTLE = 'start_battle'

# ACTIONS
CALLBACK_PHYSICAL_ATTACK = 'physical_attack'
CALLBACK_PRECISION_ATTACK = 'precision_attack'
CALLBACK_MAGICAL_ATTACK = 'magical_attack'
ATTACK_TYPE = {
    CALLBACK_PHYSICAL_ATTACK: EmojiEnum.PHYSICAL_ATTACK.value,
    CALLBACK_PRECISION_ATTACK: EmojiEnum.PRECISION_ATTACK.value,
    CALLBACK_MAGICAL_ATTACK: EmojiEnum.MAGICAL_ATTACK.value
}
ACTIONS = {
    CALLBACK_PHYSICAL_ATTACK: 'Ataque Físico',
    CALLBACK_PRECISION_ATTACK: 'Ataque de Precisão',
    CALLBACK_MAGICAL_ATTACK: 'Ataque Mágico',
}
ACTIONS_LABELS = {
    CALLBACK_PHYSICAL_ATTACK: (
        f'ATAQUE FÍSICO {EmojiEnum.PHYSICAL_ATTACK.value}'
    ),
    CALLBACK_PRECISION_ATTACK: (
        f'ATAQUE DE PRECISÃO {EmojiEnum.PRECISION_ATTACK.value}'
    ),
    CALLBACK_MAGICAL_ATTACK: f'ATAQUE MÁGICO {EmojiEnum.MAGICAL_ATTACK.value}',
}

# REACTIONS
CALLBACK_DODGE = 'dodge'
CALLBACK_DEFEND = 'defend'
DEFENSE_TYPE = {
    CALLBACK_PHYSICAL_ATTACK: EmojiEnum.PHYSICAL_DEFENSE.value,
    CALLBACK_PRECISION_ATTACK: EmojiEnum.PRECISION_DEFENSE.value,
    CALLBACK_MAGICAL_ATTACK: EmojiEnum.MAGICAL_DEFENSE.value,
}
REACTIONS = {
    CALLBACK_DODGE: 'Esquivar',
    CALLBACK_DEFEND: 'Defender'
}
REACTIONS_LABELS = {
    CALLBACK_DODGE: f'ESQUIVAR {EmojiEnum.DODGE.value}',
    CALLBACK_DEFEND: f'DEFENDER {EmojiEnum.DEFEND.value}'
}

# TEAMS
TEAMS = {
    CALLBACK_ENTER_BLUE_TEAM: f'{EmojiEnum.TEAM_BLUE.value}Azul',
    CALLBACK_ENTER_RED_TEAM: f'{EmojiEnum.TEAM_RED.value}Vermelho'
}
