REPLY_TEXTS_FIND_TREASURE_START = [
    'Durante a sua viagem, vocês se deparam com uma clareira tranquila na floresta, ',
    'Explorando uma caverna escura, vocês se deparam com uma passagem secreta, ',
    'Ao cruzar uma ponte antiga, vocês se deparam com uma ilha misteriosa, ',
    'Navegando pelo mar agitado, vocês se deparam com um navio naufragado, ',
    'No alto das montanhas, vocês se deparam com uma ruína esquecida, ',
    'Ao explorar um pântano sombrio, vocês se deparam com uma árvore gigante, ',
    'No deserto escaldante, vocês se deparam com um oásis escondido, ',
    'Enquanto atravessam uma floresta densa, vocês se deparam com uma clareira encantada, ',
    'Ao explorar uma cidade abandonada, vocês se deparam com uma mansão assombrada, ',
    'Escalando uma colina íngreme, vocês se deparam com uma caverna misteriosa, ',
    'Em uma estrada deserta, vocês se deparam com uma carroça abandonada, ',
    'No fundo de um vale isolado, vocês se deparam com uma fonte de água cristalina, ',
    'Ao atravessar uma floresta encantada, vocês se deparam com uma estátua enigmática, ',
    'Viajando pelo deserto vasto, vocês se deparam com uma ruína soterrada, ',
    'Navegando por um rio sinuoso, vocês se deparam com uma ilha desconhecida, ',
    'Enquanto exploram uma região glacial, vocês se deparam com uma caverna de gelo, ',
    'No meio de um campo verdejante, vocês se deparam com uma árvore ancestral, ',
    'Passando por um vale sombrio, vocês se deparam com um templo abandonado, ',
    'Caminhando pela praia, vocês se deparam com um naufrágio antigo, ',
    'Viajando pelas terras selvagens, vocês se deparam com uma rocha misteriosa, ',
    'Explorando um cânion profundo, vocês se deparam com uma gruta oculta, ',
    'Ao seguir um riacho, vocês se deparam com uma cachoeira majestosa, ',
    'Escalando uma montanha escarpada, vocês se deparam com uma caverna ventosa, ',
    'Cruzando uma floresta enevoada, vocês se deparam com uma clareira encantada, ',
    'Em uma cidade abandonada, vocês se deparam com uma biblioteca esquecida, ',
    'Percorrendo um deserto vasto, vocês se deparam com uma oásis escondido, ',
    'Ao explorar uma selva densa, vocês se deparam com uma ruína coberta de vegetação, ',
    'Navegando pelo mar tempestuoso, vocês se deparam com um naufrágio misterioso, ',
    'Em uma região vulcânica, vocês se deparam com uma caverna ígnea, ',
    'Durante uma caminhada na tundra congelada, vocês se deparam com um abrigo improvisado, ',
    'Viajando por uma planície vasta, vocês se deparam com uma pedra rúnica, ',
    'Ao atravessar uma floresta assombrada, vocês se deparam com um altar místico, ',
    'Em um vale escondido, vocês se deparam com uma nascente de água quente, ',
    'Caminhando por um desfiladeiro estreito, vocês se deparam com uma abertura subterrânea, ',
    'Passando por um pântano enevoado, vocês se deparam com uma árvore retorcida, ',
    'No meio de um campo de flores, vocês se deparam com um marco antigo, ',
    'Percorrendo uma região desértica, vocês se deparam com uma ruína enterrada, ',
    'Explorando uma floresta encantada, vocês se deparam com um círculo de pedras, ',
    'Enquanto seguem um rio serpenteante, vocês se deparam com uma ilha pitoresca, ',
    'Viajando por uma região montanhosa, vocês se deparam com uma passagem estreita, ',
    'Ao cruzar um planalto ventoso, vocês se deparam com um abrigo improvisado, ',
    'Em uma cidade em ruínas, vocês se deparam com uma cripta esquecida, ',
    'Caminhando por uma praia deserta, vocês se deparam com um baú enterrado, ',
    'No fundo de um vale verdejante, vocês se deparam com uma nascente de água pura, ',
    'Atravessando um pântano lamacento, vocês se deparam com uma árvore solitária, ',
    'No topo de uma colina, vocês se deparam com um monumento antigo, ',
    'Percorrendo uma floresta enigmática, vocês se deparam com um altar oculto, ',
    'Explorando uma caverna úmida, vocês se deparam com um veio de minério, ',
    'Ao seguir um riacho murmurante, vocês se deparam com uma cachoeira majestosa, ',
    'Em um deserto vasto, vocês se deparam com um oásis escondido, ',
    'Cruzando uma floresta antiga, vocês se deparam com uma pedra rúnica, ',
    'Viajando por uma região selvagem, vocês se deparam com uma caverna escondida, ',
    'Ao atravessar uma planície vasta, vocês se deparam com uma ruína coberta de hera, ',
    'Em uma cidade abandonada, vocês se deparam com um templo em ruínas, ',
    'No meio de uma selva densa, vocês se deparam com um altar misterioso, ',
    'Percorrendo uma praia deserta, vocês se deparam com um naufrágio antigo, ',
    'Caminhando por uma floresta encantada, vocês se deparam com uma clareira radiante, ',
    'Em uma região vulcânica, vocês se deparam com uma gruta ígnea, ',
    'Passando por um desfiladeiro estreito, vocês se deparam com uma passagem subterrânea, ',
    'No alto de uma montanha, vocês se deparam com um observatório abandonado, ',
    'Explorando uma floresta sombria, vocês se deparam com uma árvore centenária, ',
    'Viajando por um planalto ventoso, vocês se deparam com um monumento enigmático, ',
    'Ao seguir um rio sereno, vocês se deparam com uma nascente de água cristalina, ',
    'No meio de um campo verdejante, vocês se deparam com uma pedra rúnica, ',
    'Atravessando uma floresta antiga, vocês se deparam com um altar esculpido, ',
    'Em uma cidade em ruínas, vocês se deparam com uma câmara secreta, ',
    'Percorrendo uma região selvagem, vocês se deparam com um poço misterioso, ',
    'Explorando uma caverna escura, vocês se deparam com um brilho no chão, ',
    'Ao atravessar um desfiladeiro íngreme, vocês se deparam com um abismo profundo, ',
    'Caminhando por um pântano enevoado, vocês se deparam com um santuário oculto, ',
    'Em uma região glacial, vocês se deparam com uma gruta de gelo, ',
    'Passando por um vale tranquilo, vocês se deparam com uma ruína coberta de neve, ',
    'No alto de uma colina, vocês se deparam com um círculo de pedras, ',
    'Enquanto seguem uma trilha estreita, vocês se deparam com uma bifurcação, ',
    'Em uma cidade abandonada, vocês se deparam com uma loja misteriosa, ',
    'Atravessando uma floresta encantada, vocês se deparam com uma clareira radiante, ',
    'Viajando por uma região montanhosa, vocês se deparam com um vale verdejante, ',
    'No meio de uma planície vasta, vocês se deparam com um marco antigo, ',
    'Explorando um templo esquecido, vocês se deparam com um altar secreto, ',
    'Ao cruzar um deserto vasto, vocês se deparam com um oásis escondido, ',
    'Percorrendo uma floresta densa, vocês se deparam com uma árvore ancestral, ',
    'Passando por um riacho sereno, vocês se deparam com uma cachoeira majestosa, ',
    'Em uma cidade em ruínas, vocês se deparam com uma câmara subterrânea, ',
    'Caminhando por uma praia deserta, vocês se deparam com um naufrágio antigo, ',
    'No alto de uma montanha, vocês se deparam com uma vista panorâmica, ',
    'Explorando uma caverna escura, vocês se deparam com um brilho no chão, ',
    'Ao seguir um rio sinuoso, vocês se deparam com uma cachoeira majestosa, ',
    'Em uma floresta encantada, vocês se deparam com um círculo de cogumelos, ',
    'Percorrendo uma região selvagem, vocês se deparam com um abismo profundo, ',
    'Passando por um vale tranquilo, vocês se deparam com um monumento antigo, ',
    'No meio de um campo verdejante, vocês se deparam com um poço misterioso, ',
    'Atravessando um pântano sombrio, vocês se deparam com um santuário oculto, ',
    'Viajando por uma região vulcânica, vocês se deparam com uma gruta ígnea, ',
    'Explorando uma cidade abandonada, vocês se deparam com uma mansão sinistra, ',
    'Caminhando por uma floresta sombria, vocês se deparam com um altar esculpido, ',
    'No alto de uma colina, vocês se deparam com um círculo de pedras, ',
    'Percorrendo uma praia deserta, vocês se deparam com um baú enterrado, ',
    'Em uma região glacial, vocês se deparam com uma nascente de água pura, ',
    'Passando por um vale verdejante, vocês se deparam com uma ruína coberta de hera, ',
    'Ao explorar um templo antigo, vocês se deparam com um altar iluminado, ',
]

REPLY_TEXTS_FIND_TREASURE_MIDDLE = [
    'e investigando vocês notam ',
    'e observando com atenção vocês percebem ',
    'e ao olhar com mais detalhes vocês se deparam ',
    'e examinando cuidadosamente vocês descobrem ',
    'e inspecionando minuciosamente vocês avistam ',
    'e ao analisar com mais profundidade vocês constatam ',
    'e explorando mais a fundo vocês identificam ',
    'e ao vistoriar a área vocês detectam ',
    'e ao estudar a região vocês notam ',
    'e ao investigar cuidadosamente vocês reconhecem ',
    'e examinando minuciosamente vocês notam ',
    'e ao observar com atenção vocês percebem ',
    'e investigando com mais detalhes vocês avistam ',
    'e olhando com mais profundidade vocês descobrem ',
    'e ao inspecionar minuciosamente vocês constatam ',
    'e observando com mais detalhes vocês identificam ',
    'e ao explorar a área vocês detectam ',
    'e estudando cuidadosamente vocês notam ',
    'e ao vistoriar a região vocês reconhecem ',
    'e ao investigar com mais profundidade vocês notam ',
    'e examinando a área vocês percebem ',
    'e ao observar minuciosamente vocês avistam ',
    'e investigando com atenção vocês descobrem ',
    'e olhando com mais detalhes vocês constatam ',
    'e ao inspecionar com mais profundidade vocês identificam ',
    'e observando cuidadosamente vocês detectam ',
    'e ao explorar minuciosamente vocês notam ',
    'e estudando com mais detalhes vocês reconhecem ',
    'e ao vistoriar com mais profundidade vocês notam ',
    'e examinando a região vocês percebem ',
    'e ao observar com atenção vocês avistam ',
    'e investigando minuciosamente vocês descobrem ',
    'e olhando com mais profundidade vocês constatam ',
    'e ao inspecionar com mais detalhes vocês identificam ',
    'e observando com mais detalhes vocês detectam ',
    'e ao explorar com mais profundidade vocês notam ',
    'e estudando a área vocês reconhecem ',
    'e ao vistoriar minuciosamente vocês notam ',
    'e examinando com mais detalhes vocês percebem ',
    'e ao observar com mais profundidade vocês avistam ',
    'e investigando a região vocês descobrem ',
    'e olhando com mais detalhes vocês constatam ',
    'e ao inspecionar com atenção vocês identificam ',
    'e observando minuciosamente vocês detectam ',
    'e ao explorar com mais detalhes vocês notam ',
    'e estudando com mais profundidade vocês reconhecem ',
    'e ao vistoriar a área vocês notam ',
    'e examinando cuidadosamente vocês percebem ',
    'e ao observar a região vocês avistam ',
    'e investigando com mais detalhes vocês descobrem ',
    'e olhando com mais profundidade vocês constatam ',
    'e ao inspecionar minuciosamente vocês identificam ',
    'e observando com atenção vocês detectam ',
    'e ao explorar minuciosamente vocês notam ',
    'e estudando com mais detalhes vocês reconhecem ',
    'e ao vistoriar com mais profundidade vocês notam ',
    'e examinando a área vocês percebem ',
    'e ao observar com atenção vocês avistam ',
    'e investigando minuciosamente vocês descobrem ',
    'e olhando com mais detalhes vocês constatam ',
    'e ao inspecionar com mais profundidade vocês identificam ',
    'e observando com mais detalhes vocês detectam ',
    'e ao explorar a região vocês notam ',
    'e estudando cuidadosamente vocês reconhecem ',
    'e ao vistoriar minuciosamente vocês notam ',
    'e examinando com mais detalhes vocês percebem ',
    'e ao observar com mais profundidade vocês avistam ',
    'e investigando a área vocês descobrem ',
    'e olhando com mais profundidade vocês constatam ',
    'e ao inspecionar minuciosamente vocês identificam ',
    'e observando com atenção vocês detectam ',
    'e ao explorar minuciosamente vocês notam ',
    'e estudando com mais detalhes vocês reconhecem ',
    'e ao vistoriar com mais profundidade vocês notam ',
    'e examinando a região vocês percebem ',
    'e ao observar com atenção vocês avistam ',
    'e investigando minuciosamente vocês descobrem ',
    'e olhando com mais detalhes vocês constatam ',
    'e ao inspecionar com mais profundidade vocês identificam ',
    'e observando com mais detalhes vocês detectam ',
    'e ao explorar a área vocês notam ',
    'e estudando com mais profundidade vocês reconhecem ',
    'e ao vistoriar minuciosamente vocês notam ',
    'e examinando com mais detalhes vocês percebem ',
    'e ao observar com mais profundidade vocês avistam ',
    'e investigando a região vocês descobrem ',
    'e olhando com mais profundidade vocês constatam ',
    'e ao inspecionar com atenção vocês identificam ',
    'e observando minuciosamente vocês detectam ',
    'e ao explorar minuciosamente vocês notam ',
    'e estudando com mais detalhes vocês reconhecem ',
    'e ao vistoriar com mais profundidade vocês notam ',
    'e examinando a área vocês percebem ',
    'e ao observar com atenção vocês avistam ',
    'e investigando minuciosamente vocês descobrem ',
    'e olhando com mais detalhes vocês constatam ',
    'e ao inspecionar com mais profundidade vocês identificam ',
    'e observando com mais detalhes vocês detectam ',
    'e ao explorar a região vocês notam ',
    'e estudando com mais profundidade vocês reconhecem ',
]

REPLY_TEXTS_FIND_TREASURE_END = [
    'um baú de madeira envelhecida com ornamentos entalhados nas bordas.',
    'uma bolsa de couro gasta pelo tempo e marcada por sinais de uso.',
    'um cofre de metal, reforçado com dobradiças e fechaduras complexas.',
    'uma caixa de pedra esculpida, adornada com símbolos desconhecidos.',
    'uma arca de tecido ricamente bordado, com fios dourados reluzentes.',
    'um estojo de madeira contendo compartimentos cuidadosamente dispostos.',
    'uma sacola de linho simples, amarrada com um cordão resistente.',
    'um pote de cerâmica selado com cera, revelando marcas de selos antigos.',
    'uma urna de vidro transparente, permitindo ver o interior.',
    'uma mala de viagem de couro robusto, com alças reforçadas.',
    'um engradado de metal corroído pela ferrugem, mas ainda trancado.',
    'uma caixa esculpida de osso, exibindo figuras intrincadas entrelaçadas.',
    'um estojo de veludo negro, forrado com seda e fechado com elegância.',
    'uma caixa de pedra lapidada, refletindo luzes coloridas.',
    'uma cesta de vime trançado com uma tampa tecida em padrões complexos.',
    'um baú de ferro com inscrições rúnicas gravadas na superfície.',
    'uma bolsa de veludo vermelho com um brilho sutil e bordas desgastadas.',
    'um cofre selado com cera quente, mantendo seu conteúdo em segredo.',
    'um jarro de barro selado com um selo de cera antigo.',
    'uma maleta de madeira com cantos reforçados e alças de couro.',
    'uma caixa de metal enferrujada repousa no canto da sala.',
    'uma bolsa de couro gasta está jogada sobre uma mesa.',
    'um cofre de pedra está embutido na parede, com uma roda giratória na frente.',
    'uma arca de carvalho maciço repousa no centro da sala, com fechos de ferro.',
    'um saco de lona está pendurado em um gancho na parede.',
    'uma pequena urna de cerâmica está posicionada cuidadosamente em uma prateleira.',
    'um baú de madeira envernizada está empoleirado no topo de um pedestal.',
    'uma sacola de linho bordada está caída perto da porta.',
    'um pequeno estojo de couro está preso ao lado de uma estante, com fechos intricados.',
    'uma caixa esculpida está em exibição em um nicho na parede.',
    'um baú de metal polido está embutido no chão, com um símbolo gravado.',
    'uma bolsa de veludo está jogada despretensiosamente sobre uma cadeira.',
    'uma urna finamente trabalhada repousa sobre uma almofada de seda.',
    'um pequeno baú de madeira de cerejeira está embutido na parede, com um entalhe de folhas.',
    'uma sacola de lã está pendurada perto da lareira.',
    'um estojo de couro austero está preso a um suporte de madeira simples.',
    'uma caixa de pedra entalhada com runas está posicionada no centro da sala.',
    'uma bolsa de couro decorada está descansando em um banco de pedra.',
    'um cofre de mogno está embutido no chão, com relevos intrincados.',
    'uma pequena urna de vidro colorido está posicionada em um pedestal de metal.',
    'uma caixa de metal fortemente trancada, com marcas de uso evidentes.',
    'uma bolsa de pano simples, amarrada com um cordão de couro desgastado.',
    'um cofre de madeira nobre, esculpido com padrões geométricos.',
    'um baú de couro envelhecido, adornado com fechos de bronze.',
    'uma arca finamente martelada, refletindo a luz em padrões cintilantes.',
    'uma bolsa de camurça macia, com franjas nas bordas.',
    'um estojo de ébano, detalhado com incrustações de madrepérola.',
    'um baú de ferro fundido, gravado com símbolos misteriosos.',
    'uma sacola de linho grossa, com alças de couro cru.',
    'um jarro de cerâmica selado com um nó de corda.',
    'uma caixa de madeira polida, com um fecho delicado em formato de flor.',
    'um cofre de bronze maciço, com uma fechadura ornamental.',
    'uma bolsa de veludo azul-marinho, com um brilho sutil.',
    'uma arca de madeira entalhada, retratando cenas antigas.',
    'um estojo de metal adornado com padrões entrelaçados.',
    'um baú de couro robusto, reforçado com pregos de cobre.',
    'uma urna de mármore branco, esculpida com figuras angelicais.',
    'uma bolsa de tecido colorido, com bordados intricados.',
    'um pequeno cofre com uma inscrição enigmática.',
    'um pote de cerâmica vidrada, com um selo de cera intacto.',
    'uma caixa de madeira escura, com um entalhe de olho na tampa.',
    'um jarro de vidro soprado à mão, selado com cera colorida.',
    'uma arca de carvalho envernizada, com detalhes em cobre.',
    'uma sacola de couro desgastado, com manchas de tinta.',
    'um estojo de pedra coloridas, incrustado com maestria.',
    'um baú de ferro reforçado, com correntes em volta.',
    'uma bolsa de veludo verde-esmeralda, com bordas desfiadas.',
    'uma urna de porcelana delicada, pintada à mão.',
    'uma caixa de metal martelado, com fechos de latão.',
    'um jarro de barro decorado, com uma tampa de cortiça.',
    'um pequeno estojo de madeira escura, com dobradiças douradas.',
    'um baú de couro envernizado, com pregos prateados.',
    'uma sacola de linho bordada com fios de dourados.',
    'um cofre de pedra cinza, com inscrições enigmáticas.',
    'uma arca de mogno maciço, com entalhes de folhas.',
    'uma bolsa de seda vermelha, com um brilho intenso.',
    'uma urna de vidro fosco, com detalhes em metal escuro.',
    'um pequeno baú de madeira clara, com cantos arredondados.',
    'um estojo de couro trabalhado à mão, com costuras elaboradas.',
    'uma caixa finamente gravada, com padrões abstratos.',
    'um jarro de cerâmica decorada, com uma rolha de cortiça.',
    'um baú de madeira esculpida, representando figuras mitológicas.',
    'uma bolsa de couro preto, com um aroma distinto.',
    'uma arca de bronze envelhecido, com gravuras desgastadas.',
    'uma sacola de lona resistente, com alças de couro entrelaçado.',
    'um cofre de vidro transparente, com fechos de metal prateado.',
    'um estojo de madeira tingida, com padrões entrelaçados.',
    'um jarro de metal envernizado, com uma rolha de cortiça.',
    'um pequeno baú de madeira crua, com pregos de ferro.',
    'uma urna de pedra esculpida, representando uma figura angelical.',
    'uma caixa de couro macio, com entalhes de flores na tampa.',
    'um pote de cerâmica decorada, com um selo de cera intacto.',
    'um baú de metal ornamentado, com detalhes dourados.',
    'uma bolsa de veludo roxo, com um brilho suave.',
    'uma arca de ébano entalhado, retratando cenas de batalha.',
    'um estojo de madeira envernizada, com dobradiças de latão.',
    'um cofre de couro reforçado, com amarrações de corda.',
    'uma sacola de seda fina, com bordados delicados.',
    'um jarro de vidro colorido, com uma tampa de metal.',
    'uma caixa de pedra rústica, com runas esculpidas.',
    'um pequeno baú de mogno, com detalhes desenhados.',
    'uma urna de cerâmica vidrada, com um padrão em espiral.',
    'uma bolsa de linho cru, com um toque áspero.',
    'um estojo de couro escuro, com fechos de cobre.',
    'um baú de metal forjado, com inscrições antigas.',
    'uma arca de madeira trabalhada, com detalhes em marfim.',
    'uma sacola de camurça, com franjas na abertura.',
    'um jarro de metal polido, com uma rolha de cortiça apertada.',
    'uma caixa gravada, com padrões intrincados.',
    'um cofre de pedra esculpida, com relevos abstratos.',
    'uma bolsa de veludo cintilante, com um toque suave.',
    'uma urna de vidro translúcido, com ornamentos de metal.',
    'um pequeno baú de madeira entalhada, com um símbolo enigmático.',
    'um estojo de metal envelhecido, com gravuras desbotadas.',
    'um baú de couro gasto, com amarrações de corda.',
    'uma sacola de linho resistente, com alças de couro entrançado.',
    'um jarro de cerâmica simples, com uma tampa de cortiça.',
    'uma caixa de madeira envernizada, com detalhes prateados.',
    'um cofre de vidro fosco, com um fecho de metal.',
    'uma arca de bronze esculpido, retratando figuras mitológicas.',
    'uma bolsa de couro envelhecido, com marcas de uso.',
    'uma urna de madeira escura, com entalhes de animais.',
    'um pequeno baú de pedra, com uma inscrição enigmática.',
    'um estojo de couro macio, com costuras simples.',
    'um baú de metal reforçado, com correntes enferrujadas.',
    'uma sacola de veludo macio, com um brilho aveludado.',
    'um jarro de barro simples, com uma rolha de cortiça.',
    'uma caixa de metal envelhecido, com fechos de bronze.',
    'um cofre de couro trabalhado, com detalhes em relevo.',
    'uma arca de madeira nobre, esculpida com padrões florais.',
    'uma bolsa de pano resistente, com amarrações de corda.',
    'um estojo de pedra esculpida, com símbolos rúnicos.',
    'um baú de vidro transparente, com detalhes de metal.',
    'uma urna de cerâmica vidrada, com um padrão geométrico.',
    'um pequeno baú de mogno, com dobradiças de latão.',
    'uma sacola de couro liso, com um toque suave.',
    'um jarro de metal ornamentado, com uma tampa de cortiça.',
    'uma caixa trabalhada com entalhes detalhados.',
    'um cofre de pedra esculpida, com inscrições antigas.',
    'uma arca de madeira envernizada, com detalhes em marfim.',
]
