from bot.functions.chat import CALLBACK_KEY_LIST


GODS_NAME = 'Thoth & Seshat'
SECTION_TEXT_PUZZLE = 'DESAFIO'
SECTION_TEXT_PUZZLE_XP = 'XP DESAFIO'
SECTION_TEXT_PUZZLE_PUNISHMENT = 'PUNIÇÃO'

PATTERN_PUZZLE = (
    f'{{{CALLBACK_KEY_LIST.index("row")}:\d'
)


GOD_START_NARRATION_TEXTS = [
    'GOD START LOREM 1',
    'GOD START LOREM 2',
]


GOD_GREETINGS_TEXTS = [
    'GREETINGS LOREM 1',
    'GREETINGS LOREM 2',
]


GOD_GOOD_MOVE_FEEDBACK_TEXTS = [
    'GOOD FEEDBACK LOREM 1',
    'GOOD FEEDBACK LOREM 2',
]


GOD_BAD_MOVE_FEEDBACK_TEXTS = [
    'BAD FEEDBACK LOREM 1',
    'BAD FEEDBACK LOREM 2',
]

GOD_WINS_FEEDBACK_TEXTS = [
    'WINS FEEDBACK LOREM 1',
    'WINS FEEDBACK LOREM 2',
]

GODS_LOSES_FEEDBACK_TEXTS = [
    'LOSES FEEDBACK LOREM 1',
    'LOSES FEEDBACK LOREM 2',
]
