from bot.functions.chat import CALLBACK_KEY_LIST


GODS_NAME = 'Thoth & Seshat'
SECTION_TEXT_PUZZLE = 'DESAFIO'
SECTION_TEXT_PUZZLE_XP = 'XP DESAFIO'
PATTERN_PUZZLE = (
    f'{{{CALLBACK_KEY_LIST.index("row")}:\d'
)


GOD_START_NARRATION_TEXTS = [
    'Do véu da aurora, surgem duas figuras radiantes, Thoth e Seshat, deuses ancestrais.',
    'Thoth, o deus da sabedoria e da magia, com sua cabeça de íbis e porte imponente, emana uma aura de conhecimento infinito.',
    'Seshat, a deusa da escrita e da medição, adornada com uma coroa de sete pontas, segura um papiro e uma paleta, símbolos de sua erudição.',
    'Seus passos leves ecoam pelos corredores do tempo, guiando-os através dos segredos do universo.',
    'Thoth levanta seu cajado, conjurando hieróglifos luminosos que dançam no ar, revelando os mistérios da criação.',
    'Seshat desenrola seu papiro, traçando linhas precisas que mapeiam o cosmos e desvendam os segredos das estrelas.',
    'Juntos, Thoth e Seshat tecem a tapeçaria do conhecimento, entrelaçando magia e ciência em uma sinfonia cósmica.',
    'Sua presença inspira admiração e reverência em todos que os testemunham, desde os simples mortais até os faraós mais poderosos.',
    'Através de seus ensinamentos, Thoth e Seshat moldam a civilização egípcia, guiando-a na busca por justiça, prosperidade e iluminação.',
    'Bibliotecas e templos florescem sob sua tutela, erguendo-se como monumentos à sabedoria eterna.',
    'O Nilo flui com mais vigor, seus campos verdejam com abundância, e a paz reina em todo o reino, graças às bênçãos de Thoth e Seshat.',
    'As artes e as ciências florescem, impulsionadas pela inspiração divina, eternizando a glória.',
    'Thoth e Seshat viajam através dos tempos, deixando rastros de sua sabedoria em cada era, guiando a humanidade em sua jornada evolutiva.',
    'Seus ensinamentos ecoam através dos séculos, inspirando filósofos, artistas e cientistas em sua busca por compreensão.',
    'Em cada sussurro do vento, em cada raio de sol, a presença de Thoth e Seshat se faz sentir, lembrando-nos do poder transformador do conhecimento.',
    'Sua sabedoria atemporal transcende as barreiras do tempo e do espaço, unindo o passado, o presente e o futuro em um elo eterno.',
    'Thoth e Seshat são os guardiões da verdade, os luminares que iluminam o caminho da humanidade em direção à sua mais alta realização.',
    'Que suas bênçãos continuem a nos guiar, inspirando-nos a buscar a sabedoria, a justiça e a harmonia em todas as nossas ações.',
    'Que a luz de Thoth e Seshat ilumine nossos corações e mentes, conduzindo-nos a um futuro radiante de paz e prosperidade.',
    'Honremos a memória desses deuses ancestrais, guardando seus ensinamentos em nossos corações e perpetuando sua sabedoria para as próximas gerações.',
    'O céu se abriu em um clarão incandescente, banhando a terra em uma luz dourada celestial. Uma melodia celestial ecoou pelo ar, preenchendo cada coração com uma sensação de paz e admiração.',
    'Do clarão, surgiram duas figuras majestosas, flutuando serenamente sobre a terra. Thoth, o deus da sabedoria e da magia, com sua pele azul e olhos brilhantes como estrelas, era a personificação da inteligência e do conhecimento. Ao seu lado, Seshat, a deusa da escrita e da medição, com sua veste branca e coroa dourada, irradiava sabedoria e precisão.',
    'As pessoas observavam com pasmo, seus rostos marcados por uma mistura de medo e reverência. Nunca antes haviam presenciado tal espetáculo divino. A presença de Thoth e Seshat era uma bênção e um aviso ao mesmo tempo.',
    'Thoth ergueu sua mão, e um rolo de papiro surgiu em sua palma. Ele desenrolou o papiro e começou a ler em voz alta, sua voz poderosa ecoando pelo vale. As palavras de Thoth eram sabedoria pura, ensinando sobre a importância do conhecimento, da justiça e da verdade.',
    'Seshat, por sua vez, observava a cena com um sorriso enigmático. Em suas mãos, ela segurava uma tábua de escrever e um estilete. Com movimentos precisos e elegantes, ela anotava as palavras de Thoth, preservando-as para a posteridade.',
    'As pessoas ouviam atentamente, absorvendo cada palavra de Thoth e Seshat. Eles sabiam que essas palavras eram preciosas, um guia para uma vida melhor e mais justa.',
    'Quando Thoth terminou de ler, um silêncio solene se abateu sobre a multidão. As pessoas ponderavam as palavras que haviam ouvido, sabendo que suas vidas nunca mais seriam as mesmas.',
    'Com um aceno de cabeça, Thoth e Seshat se despediram e desapareceram no clarão celestial. A luz dourada se dissipou, deixando apenas a memória de sua presença divina.',
    'As pessoas voltaram para suas casas, carregando consigo as palavras de sabedoria de Thoth e Seshat. Eles sabiam que o mundo havia mudado para sempre com a aparição dos dois deuses.',
    'A partir daquele dia, Thoth e Seshat se tornaram símbolos de sabedoria e conhecimento para o povo. Seus ensinamentos foram transmitidos de geração em geração, moldando a cultura e a sociedade por séculos.',
    'A aparição de Thoth e Seshat foi um evento marcante na história da humanidade, um lembrete do poder da sabedoria e do conhecimento para transformar o mundo.',
    'As palavras de Thoth e Seshat continuam ecoando até hoje, inspirando as pessoas a buscar a verdade, a justiça e a paz.',
    'A história de Thoth e Seshat é uma fábula atemporal sobre o poder da sabedoria e do conhecimento para transformar o mundo.',
    'Seus ensinamentos nos lembram da importância de buscar a verdade, a justiça e a paz, e de usar o conhecimento para o bem da humanidade.',
    'A aparição de Thoth e Seshat foi um evento milagroso que mudou o curso da história.',
    'Seus ensinamentos continuam a nos inspirar e nos guiar até hoje.',
    'A história de Thoth e Seshat é um lembrete do poder da sabedoria e do conhecimento para transformar vidas.',
    'Seus ensinamentos nos ensinam a sermos melhores pessoas e a construir um mundo melhor.',
    'Thoth e Seshat são símbolos de sabedoria e conhecimento que continuam a nos inspirar até hoje.',
    'A história de Thoth e Seshat é uma fábula atemporal que nos ensina sobre o poder da sabedoria e do conhecimento para transformar o mundo.',
    'Do véu da aurora, duas figuras emergem, banhadas na luz dourada do nascer do sol. São Thoth, o deus da sabedoria e da escrita, e Seshat, a deusa do conhecimento e da medição.',
    'Thoth, com sua cabeça de íbis e porte imponente, segura um bastão e um pergaminho, símbolos de seu poder intelectual. Seshat, adornada com uma coroa de sete pontas e um vestido verde esmeralda, carrega uma tábua e um estilete, instrumentos de sua precisão e registro.',
    'Seus passos leves ecoam pelos corredores do templo, enquanto os sacerdotes se prostram em reverência. O ar se carrega com uma energia mística, um zumbido de poder divino.',
    'Thoth ergue sua voz, profunda e ressonante, como o som de um rio caudaloso. Ele fala sobre os segredos do universo, sobre a ordem e a harmonia que regem o cosmos.',
    'Seshat, com sua voz suave e melodiosa, complementa as palavras de Thoth. Ela fala sobre a importância do conhecimento, sobre a busca incessante pela verdade.',
    'Juntos, eles tecem uma tapeçaria de sabedoria, tecendo os fios da matemática, da astronomia, da medicina e da magia.',
    'Os sacerdotes escutam com atenção, absorvendo cada palavra como se fosse água em terra seca. Seus corações se abrem para o conhecimento, suas mentes se expandem com as novas ideias.',
    'Thoth e Seshat caminham entre os fiéis, tocando suas cabeças com seus cajados. Uma onda de energia os invade, despertando seus intelectos e aguçando seus sentidos.',
    'Doentes são curados, aleijados são curados, e aqueles que estão perdidos encontram seu caminho. O poder de Thoth e Seshat flui através de todos, trazendo cura e iluminação.',
    'Ao entardecer, Thoth e Seshat se retiram, deixando para trás um rastro de luz e sabedoria. Os sacerdotes permanecem em silêncio, contemplando as maravilhas que presenciaram.',
    'O templo se transforma em um farol de conhecimento, um centro de aprendizado para todos que buscam a verdade.',
    'A história da aparição de Thoth e Seshat se espalha por todo o país, inspirando gerações de estudiosos e filósofos.',
    'Seus ensinamentos se tornam a base da civilização egípcia, guiando o povo em seu caminho para a grandeza.',
    'Thoth e Seshat são eternizados como deuses da sabedoria, seus nomes reverenciados por todos que buscam a luz do conhecimento.',
    'Sua aparição serve como um lembrete do poder transformador da educação e do potencial ilimitado da mente humana.',
    'Através dos tempos, suas histórias continuam a inspirar, motivando as pessoas a buscar o conhecimento e a usar sua sabedoria para o bem.',
    'O legado de Thoth e Seshat vive em cada um de nós, na busca incessante pela verdade e na vontade de compartilhar nosso conhecimento com o mundo.',
    'Que a luz de sua sabedoria continue a iluminar o nosso caminho e a nos guiar em direção a um futuro mais brilhante.',
    'Que seus ensinamentos nos inspirem a ser melhores pessoas, a usar nossa inteligência para criar um mundo mais justo e equitativo.',
    'Que a memória de Thoth e Seshat seja para sempre uma bênção para a humanidade.',
]


GOD_GREETINGS_TEXTS = [
    'Aventureiros, desvendem os segredos da tumba antiga e libertem os tesouros ancestrais! A recompensa em ouro e sabedoria será grandiosa, mas a maldição dos faraós recairá sobre vocês se falharem.',
    'O enigma da esfinge guarda a entrada para o labirinto encantado. Desvendem seus mistérios e encontrem a glória eterna, ou a fúria da fera os consumirá.',
    'A biblioteca perdida esconde um conhecimento inestimável. Descifrem seus pergaminhos e adquiram sabedoria infinita, mas cuidado com a ira dos bibliotecários espectrais que guardam seus segredos.',
    'A torre encantada é lar de um tesouro mágico. Escalem seus andares e desvendem seus enigmas para alcançar a fortuna, mas a queda será fatal se a torre os rejeitar.',
    'O mapa do pirata fantasma guia para um baú repleto de moedas de ouro. Sigam suas pistas e desvendem seus segredos para alcançar a riqueza, mas a maldição do mar os afogará se falharem.',
    'A floresta proibida esconde um portal para uma dimensão celestial. Desvendem seus segredos e alcancem a iluminação, mas a escuridão eterna os consumirá se a floresta os rejeitar.',
    'O enigma do dragão milenar guarda a entrada para um reino perdido. Respondam suas perguntas e encontrem a paz eterna, mas a fúria do dragão os incinerará se falharem.',
    'A cidade afundada esconde um artefato de poder inimaginável. Nadam em suas ruínas e desvendem seus mistérios para alcançar a glória, mas a maldição das águas os afogará se falharem.',
    'O obelisco antigo emite um sinal misterioso. Desvendem seus símbolos e encontrem a chave para a imortalidade, mas a ira dos deuses os fulminará se falharem.',
    'A caverna escura esconde um portal para um mundo de sonhos. Entrem em seus segredos e encontrem a felicidade eterna, mas a loucura os consumirá se a caverna os rejeitar.',
    'O jardim encantado esconde a chave para a paz interior. Desvendem seus segredos e encontrem a serenidade, mas a maldição das flores os transformará em pedra se falharem.',
    'A montanha sagrada esconde um templo de sabedoria. Escalem seus picos e desvendem seus enigmas para alcançar a iluminação, mas a queda será fatal se a montanha os rejeitar.',
    'O rio encantado esconde um portal para um reino de fadas. Naveguem em suas águas e desvendem seus segredos para alcançar a magia, mas a maldição das águas os afogará se falharem.',
    'O vulcão adormecido esconde um tesouro de fogo. Desvendem seus segredos e encontrem a fortuna, mas a lava os consumirá se o vulcão despertar.',
    'A floresta mágica esconde um portal para um mundo de animais falantes. Entrem em seus segredos e encontrem a amizade eterna, mas a maldição da floresta os transformará em animais se falharem.',
    'O castelo fantasma esconde a chave para a redenção. Explorem seus corredores e desvendem seus mistérios para alcançar a paz interior, mas a maldição dos fantasmas os assombrará para sempre se falharem.',
    'O deserto proibido esconde um portal para um oásis de paz. Cruzem suas areias e desvendem seus segredos para encontrar a água da vida, mas a tempestade de areia os consumirá se falharem.',
    'O pântano maldito esconde um portal para um mundo de pesadelos. Explorem seus segredos e enfrentem seus medos para alcançar a coragem, mas a loucura os consumirá se falharem.',
    'A cidade perdida esconde a chave para a juventude eterna. Desvendem seus segredos e encontrem a fonte da vida, mas a maldição da cidade os transformará em múmias se falharem.',
    'O labirinto infinito esconde a chave para a liberdade. Corram por seus corredores e desvendem seus segredos para escapar, mas a fome e a sede os consumirão se falharem.',
    'Desvendem os segredos da Esfinge e libertem tesouros ancestrais! Glória e sabedoria os aguardam, mas o fracasso trará a ira dos deuses.',
    'Nas catacumbas, um enigma espera por desbravadores. Desvendem seus mistérios e sejam recompensados com riquezas além da imaginação. Mas cuidado, a fúria divina recai sobre quem falhar.',
    'O labirinto esmeralda esconde um portal para um reino de tesouros. Desvendem seus segredos e sejam agraciados com fortuna e poder. Mas se sucumbirem à ilusão, a maldição eterna os consumirá.',
    'A Torre da Lua sussurra segredos aos bravos que a escalarem. Conquistem seus desafios e sejam recompensados com conhecimento e poder inigualáveis. Mas a queda dos fracos ecoará na eternidade.',
    'Na Floresta Sussurrante, um enigma musical aguarda por desvendadores. Descifrem a melodia e sejam recompensados com paz e prosperidade. Mas a discórdia dos falhos os entregará ao caos eterno.',
    'O Deserto das Areias Escaldantes esconde um oásis secreto com tesouros. Desvendem seus segredos e sejam recompensados com riquezas e vida eterna. Mas a morte cruel aguarda quem se perder na areia.',
    'O Cânion das Sombras ecoa com os segredos dos antigos. Desvendem seus mistérios e sejam agraciados com sabedoria e poder além da compreensão mortal. Mas a escuridão eterna consumirá quem se perder.',
    'O Rio de Fogo guarda um portal para um reino de fogo e lava. Desvendem seus segredos e sejam recompensados com poder inimaginável. Mas a ira dos vulcões os consumirá se falharem.',
    'O Pico Nevado esconde um templo ancestral com tesouros em suas geleiras. Desvendem seus segredos e sejam agraciados com riquezas e vida eterna. Mas a neve traiçoeira os levará à morte se falharem.',
    'A Caverna das Sombras guarda um enigma milenar em suas profundezas. Desvendem seus segredos e sejam recompensados com sabedoria e poder além da compreensão mortal. Mas a escuridão eterna os consumirá se falharem.',
    'O Bosque Encantado esconde um portal para um reino de fadas e magia. Desvendem seus segredos e sejam agraciados com dons mágicos e vida eterna. Mas a ira das fadas os transformará em pedra se falharem.',
    'O Pântano Putrefato guarda um enigma maldito em suas águas. Desvendem seus segredos e sejam recompensados com poder além da compreensão mortal. Mas a maldição eterna os consumirá se falharem.',
    'O Cemitério dos Mortos guarda um portal para o além em suas tumbas. Desvendem seus segredos e sejam agraciados com a vida após a morte. Mas a morte eterna os consumirá se falharem.',
    'O Castelo Assombrado esconde um enigma fantasmagórico em seus corredores. Desvendem seus segredos e sejam recompensados com paz e prosperidade. Mas a discórdia dos falhos os entregará ao caos eterno.',
    'A Cidade Perdida guarda um portal para um reino de ouro em suas ruínas. Desvendem seus segredos e sejam agraciados com riquezas e vida eterna. Mas a morte cruel aguarda quem se perder nas ruínas.',
    'O Vulcão Adormecido esconde um enigma de fogo em suas profundezas. Desvendem seus segredos e sejam recompensados com poder inimaginável. Mas a ira dos vulcões os consumirá se falharem.',
    'O Oceano Tempestuoso guarda um portal para um reino de tesouros submersos. Desvendem seus segredos e sejam agraciados com riquezas e vida eterna. Mas a fúria do mar os consumirá se falharem.',
    'A Floresta Sussurrante esconde um enigma musical em suas árvores. Descifrem a melodia e sejam recompensados com paz e harmonia. Mas a discórdia os levará à escuridão eterna.',
    'Desvendem os segredos da Montanha Sagrada e alcancem o topo para receberem sabedoria divina. Mas cuidado, pois o caminho é árduo e repleto de perigos.',
    'Aventureiros intrépidos, preparem-se para desvendar os enigmas da Esfinge milenar! Apenas aqueles com mentes afiadas e corações valentes conseguirão decifrar seus segredos ancestrais. A recompensa? Tesouros além da imaginação, conhecimento arcano e glória eterna! Mas cuidado, aventureiros: a ira da Esfinge recairá sobre os fracos e desprovidos de sabedoria. A punição? Uma eternidade vagando pelo deserto, perdidos e esquecidos.',
    'Nas profundezas da terra, sob o véu do mistério, jazem as catacumbas amaldiçoadas. Cheias de armadilhas mortais e segredos obscuros, guardam em seu interior tesouros inimagináveis e relíquias de poder inigualável. Somente aqueles com inteligência aguçada, bravura inabalável e um coração puro conseguirão navegar pelos seus labirintos e desvendar seus enigmas. A recompensa? Fortuna além dos sonhos mais loucos, poder inigualável e a chance de se tornarem lendas. Mas cuidado, aventureiros: a fúria dos deuses antigos recairá sobre aqueles que perturbarem o descanso eterno dos mortos. A punição? Uma eternidade aprisionados nas catacumbas, condenados a vagar entre os ossos e as sombras por toda a eternidade.',
    'No coração da selva esmeralda, um portal místico se esconde entre as árvores e cipós, guardando a entrada para um reino de tesouros inimagináveis e beleza estonteante. Somente aqueles com um espírito puro, um coração corajoso e um profundo respeito pela natureza conseguirão encontrar o portal e desvendar seus segredos. A recompensa? Fortuna além dos sonhos mais loucos, poder inigualável e a chance de viver em harmonia com a natureza. Mas cuidado, aventureiros: a ilusão os enganará e os condenará se não forem cautelosos. A punição? Uma eternidade presos na selva, vagando sem rumo e sem esperança, amaldiçoados pela fúria da floresta.',
    'Erguendo-se majestosamente acima das nuvens, a Torre da Lua guarda em seu interior os segredos mais profundos do universo e o conhecimento mais antigo da humanidade. Somente aqueles com mentes brilhantes, espíritos elevados e um profundo desejo de sabedoria conseguirão alcançar o topo da torre e desvendar seus mistérios. A recompensa? Conhecimento e poder inigualáveis, a chance de se tornarem lendas e a oportunidade de transcender os limites da mortalidade. Mas cuidado, aventureiros: a queda dos fracos será eterna. A punição? Uma queda vertiginosa da torre, condenando seus corpos à morte e seus espíritos ao esquecimento eterno.',
    'Na floresta sussurrante, os segredos da paz eterna se escondem entre as árvores e o vento. Somente aqueles com corações puros, almas pacíficas e uma profunda conexão com a natureza conseguirão decifrar a melodia da floresta e encontrar o caminho para a paz. A recompensa? Paz eterna, felicidade inabalável e a chance de viver em harmonia com o universo. Mas cuidado, aventureiros: a discórdia os entregará ao caos eterno. A punição? Uma vida atormentada por conflitos internos e externos, sem nunca encontrar a paz que tanto desejam.',
    'Sob o sol abrasador e a areia escaldante, o Deserto das Areias Escaldantes esconde um oásis de riquezas inimagináveis. Somente aqueles com força física, resistência inabalável e um profundo respeito pela natureza conseguirão atravessar o deserto e encontrar o oásis. A recompensa? Fortuna além dos sonhos mais loucos, poder inigualável e a chance de se tornarem lendas. Mas cuidado, aventureiros: a morte os consumirá na areia se não forem fortes. A punição? Uma morte terrível pela sede, pelo calor e pelas tempestades de areia, condenando seus corpos à desidratação e seus espíritos ao esquecimento eterno.',
]


GOD_GOOD_MOVE_FEEDBACK_TEXTS = [
    'Parabéns pela sua fluidez e precisão!',
    'Admiro a sua força e controle!',
    'Que elegância e leveza em cada passo!',
    'Sua criatividade e expressividade me inspiram!',
    'Que ritmo contagiante e vibrante!',
    'Impressionante como vocês dominam o espaço!',
    'Parabéns pela sintonia e trabalho em equipe!',
    'Que sincronia impecável e perfeita!',
    'Vocês transmitem pura energia e entusiasmo!',
    'Admiro a sua dedicação e paixão pelo movimento!',
    'Que performance impecável e arrebatadora!',
    'Vocês são a personificação da graça e da beleza!',
    'Sua técnica e habilidade me deixam sem palavras!',
    'Que força e explosão em cada movimento!',
    'Parabéns pela sua fluidez e leveza!',
    'Admiro a sua precisão e controle!',
    'Que elegância e leveza em cada passo!',
    'Sua criatividade e expressividade me inspiram!',
    'Que ritmo contagiante e vibrante!',
    'Impressionante como vocês dominam o espaço!',
    'Parabéns pela sintonia e trabalho em equipe!',
    'Que sincronia impecável e perfeita!',
    'Vocês transmitem pura energia e entusiasmo!',
    'Admiro a sua dedicação e paixão pelo movimento!',
    'Que performance impecável e arrebatadora!',
    'Vocês são a personificação da graça e da beleza!',
    'Sua técnica e habilidade me deixam sem palavras!',
    'Que força e explosão em cada movimento!',
    'Parabéns pela sua fluidez e leveza!',
    'Admiro a sua precisão e controle!',
    'Uau, esse movimento foi preciso e fluido!',
    'Incrível como vocês se coordenaram nesse movimento!',
    'Que sincronia perfeita! Parecia um balé!',
    'Adorei a força e a explosão nesse movimento!',
    'Vocês dominam a técnica desse movimento com maestria!',
    'Esse movimento foi executado com tanta leveza e elegância!',
    'Impressionante a precisão e o controle que vocês demonstraram!',
    'Que movimento criativo e original! Gostei muito da ideia!',
    'Vocês realmente dominam a arte desse movimento!',
    'Parabéns pela fluidez e naturalidade do movimento!',
    'Incrível como vocês conseguem fazer esse movimento parecer tão fácil!',
    'Que explosão de energia nesse movimento!',
    'Vocês transmitem muita confiança e segurança na execução desse movimento!',
    'Adorei a precisão e a fluidez dos seus movimentos!',
    'Vocês são realmente talentosos para esse tipo de movimento!',
    'Que movimento bonito e harmonioso!',
    'Incrível como vocês conseguem combinar força e elegância nesse movimento!',
    'Parabéns pela técnica impecável na execução desse movimento!',
    'Vocês realmente dominam a arte da coreografia!',
    'Esse movimento foi executado com tanta maestria que me deixou sem palavras!',
    'Adorei a criatividade e a originalidade desse movimento!',
    'Vocês são realmente inspiradores com a forma como executam esse movimento!',
    'Que movimento contagiante! Dá vontade de levantar e dançar junto com vocês!',
    'Vocês transmitem muita alegria e energia na execução desse movimento!',
    'Parabéns pela performance impecável!',
    'Vocês são realmente profissionais naquilo que fazem!',
    'Esse movimento foi executado com tanta perfeição que me emocionou!',
    'Vocês são verdadeiros artistas do movimento!',
    'Que privilégio ter assistido a essa performance incrível!',
    'Vocês me deixaram sem fôlego com a beleza e a perfeição desse movimento!',
    'Vocês dominaram a coreografia com maestria!',
    'Seus movimentos são tão fluidos e graciosos!',
    'A sintonia entre vocês é incrível!',
    'Vocês transbordam energia e entusiasmo!',
    'Sua paixão pela dança é contagiante!',
    'Cada passo é executado com precisão e elegância!',
    'Vocês criaram uma verdadeira obra de arte com seus movimentos!',
    'Sua performance foi simplesmente impecável!',
    'Vocês me inspiraram com a sua criatividade e talento!',
    'Parabéns por essa apresentação memorável!',
    'Vocês são dançarinos excepcionais!',
    'Seu talento é indiscutível!',
    'Vocês me deixaram sem palavras com a sua performance!',
    'Vocês são a personificação da graça e da leveza!',
    'Seus movimentos são tão expressivos e contagiantes!',
    'Vocês dominam a arte da dança com perfeição!',
    'Parabéns por essa conquista!',
    'Vocês merecem todos os aplausos!',
    'Continuem dançando e inspirando a todos!',
    'Vocês são um verdadeiro show de talento!',
    'Sua energia e entusiasmo são contagiantes!',
    'Vocês me fizeram sorrir e me divertir com a sua performance!',
    'Vocês são a prova de que a dança é uma arte que emociona!',
    'Obrigada por esse presente maravilhoso!',
    'Vocês me fizeram sentir a mágica da dança!',
    'Parabéns por terem realizado o seu sonho!',
    'Continuem brilhando e conquistando o mundo com a sua dança!',
    'Vocês são a inspiração para a próxima geração de dançarinos!',
    'O mundo precisa de mais dançarinos como vocês!',
    'Vocês são simplesmente incríveis!',
]


GOD_BAD_MOVE_FEEDBACK_TEXTS = [
    'Essas jogadas desorganizadas estão custando o jogo!',
    'Passem a bola, individualismo não leva a lugar nenhum!',
    'Falta de comunicação! Conversem entre si e joguem como um time!',
    'Defesa fraca! Precisamos marcar com mais garra e determinação!',
    'Erros básicos estão nos custando caro! Concentrem-se e joguem com mais atenção!',
    'Falta de criatividade! Precisamos de jogadas mais ousadas para furar essa defesa!',
    'Lentidão na transição! Sejam mais rápidos para aproveitar os contra-ataques!',
    'Imprecisão nos passes! Precisamos de passes mais precisos para criar oportunidades!',
    'Falta de finalização! Treinem mais a finalização para converter as chances em gols!',
    'Desmotivação no time! Precisamos de mais energia e entusiasmo para virar esse jogo!',
    'Falta de liderança! Precisamos de alguém que inspire e comande o time dentro de campo!',
    'Táticas erradas! Mudanças urgentes são necessárias para reverter esse quadro!',
    'Subestimação do adversário! Nunca subestimem seus oponentes, sempre deem o seu melhor!',
    'Falta de preparo físico! Precisamos de mais condicionamento para aguentar o ritmo do jogo!',
    'Arrogância e falta de humildade! Reconheçam seus erros e aprendam com eles!',
    'Desrespeito aos companheiros! O trabalho em equipe é fundamental para o sucesso!',
    'Falta de disciplina! Sigam as instruções do técnico e joguem com disciplina!',
    'Descontrole emocional! Mantenham a calma e a concentração em todas as jogadas!',
    'Negação da realidade! Aceitem seus erros e busquem soluções para melhorar!',
    'Falta de ambição! Sejam ambiciosos e busquem sempre a vitória!',
    'Conformismo com a derrota! Nunca desistam, lutem até o fim!',
    'Falta de foco no objetivo! Mantenham o foco no objetivo final e joguem com determinação!',
    'Medo de errar! Erros fazem parte do jogo, aprendam com eles e sigam em frente!',
    'Desconfiança entre os jogadores! Confiem uns nos outros e joguem em conjunto!',
    'Falta de comunicação com a comissão técnica! Diálogo aberto é fundamental para o sucesso!',
    'Falta de investimento no time! Recursos e infraestrutura adequados são essenciais!',
    'Falta de planejamento estratégico! Um plano de ação bem definido é crucial para o sucesso!',
    'Falta de comprometimento da diretoria! Apoio e investimento da diretoria são fundamentais!',
    'Falta de identidade do time! Um estilo de jogo definido e uma filosofia clara são importantes!',
    'Falta de paixão pelo esporte! Amor ao jogo e entrega são a base do sucesso!',
    'Esqueceram de aquecer antes do jogo? Essa performance foi um desastre!',
    'Passaram o jogo inteiro sem comunicação, como esperavam vencer?',
    'Tantas chances perdidas, parece que estavam jogando contra si mesmos!',
    'Defesa fraca demais, qualquer um passava!',
    'Ataque sem criatividade, só chutes sem direção!',
    'Treinador errou nas substituições, o time perdeu o ritmo!',
    'Erros básicos repetidos, falta de foco e comprometimento!',
    'Joga como se estivessem em um piquenique, sem vontade de vencer!',
    'Parece que estavam mais preocupados em não se machucar do que em jogar!',
    'Falta de garra, paixão e amor pelo jogo, decepcionante!',
    'Fizeram o adversário se sentir em casa, com tantos erros e passividade!',
    'Jogaram como se estivessem dormindo em campo, sem intensidade!',
    'Falta de organização e sincronia no time, jogaram cada um por si!',
    'Perderam a bola fácil, entregaram o jogo pro adversário!',
    'Falta de técnica e fundamentos, precisam treinar mais!',
    'Jogaram sem raça, sem garra, sem vontade de vencer!',
    'Parece que estavam jogando por obrigação, sem entusiasmo!',
    'Fizeram o torcedor passar raiva com tantas jogadas erradas!',
    'Decepcionante, precisam melhorar muito para alcançar os objetivos!',
    'Falta de ambição e determinação, jogaram sem alma!',
    'Mereceram a derrota, jogaram muito mal!',
    'Precisam de um choque de realidade, essa performance foi inaceitável!',
    'Falta de liderança e organização no time, jogaram sem rumo!',
    'Fizeram o adversário se sentir superior, com tantos erros!',
    'Jogaram sem inteligência, sem estratégia, sem nada!',
    'Decepção total, essa foi a pior partida da temporada!',
    'Precisam de um novo treinador, esse time precisa de mudanças!',
    'Falta de investimento no time, os jogadores precisam de melhores condições!',
    'Diretoria precisa dar um jeito, essa situação não pode continuar!',
    'Precisam de uma reformulação geral, esse time não tem futuro!',
    'Parem de arrastar os pés, essa indecisão está nos custando tempo e oportunidades.',
    'Vocês estão se movendo como tartarugas, vamos acelerar o ritmo antes que seja tarde demais.',
    'Essa falta de sincronismo está criando um caos desnecessário, precisamos trabalhar em conjunto.',
    'Evitem a procrastinação, o trabalho acumulado só vai gerar mais estresse e atrasos.',
    'Abandonem essa estratégia ultrapassada, precisamos de ideias inovadoras para ter sucesso.',
    'Chega de negligência, vamos dar atenção aos detalhes antes que os problemas se tornem maiores.',
    'Evitem a comunicação ineficaz, precisamos de clareza e objetividade para evitar mal-entendidos.',
    'Abram mão da estagnação, vamos buscar o crescimento e a evolução constante.',
    'Deixem de lado a passividade, assumam a responsabilidade e tomem as rédeas da situação.',
    'Superem a falta de foco, concentrem-se nas tarefas prioritárias para alcançarmos nossos objetivos.',
    'Evitem a desmotivação, alimentem a paixão e o entusiasmo para manter o time engajado.',
    'Abandonem a apatia, busquem a proatividade e a iniciativa para fazer a diferença.',
    'Chega de negativismo, cultivem o otimismo e a positividade para superar os desafios.',
    'Evitem a desorganização, implementem um sistema eficiente para otimizar o trabalho.',
    'Abandonem a falta de planejamento, definam metas claras e estratégias eficazes para o sucesso.',
    'Deixem de lado a comunicação precária, invistam em ferramentas e canais eficientes para se conectar.',
    'Superem a falta de feedback, pratiquem a comunicação aberta e honesta para o crescimento individual e do grupo.',
    'Evitem a falta de reconhecimento, valorizem os esforços e conquistas de cada membro da equipe.',
    'Abandonem a cultura do erro, aprendam com os erros e busquem a melhoria contínua.',
    'Chega de acomodação, busquem a inovação e a disrupção para se destacar no mercado.',
    'Evitem a falta de adaptabilidade, sejam flexíveis e ágeis para lidar com as mudanças e desafios.',
    'Abandonem a resistência à mudança, abracem as novas oportunidades e evoluam com o tempo.',
    'Deixem de lado a falta de resiliência, superem os obstáculos e aprendam com as dificuldades.',
    'Superem a falta de colaboração, trabalhem em equipe e unam forças para alcançar o sucesso.',
    'Evitem a falta de comunicação interdepartamental, alinhem as ações e estratégias para um trabalho coeso.',
    'Abandonem a cultura da culpa, busquem soluções e aprendam com os erros sem culpar ninguém.',
    'Chega de falta de empatia, coloquem-se no lugar do outro para construir relações mais fortes.',
    'Evitem a falta de respeito, tratem todos com cordialidade e profissionalismo.',
    'Abandonem a falta de comprometimento, assumam suas responsabilidades e cumpram seus prazos.',
    'Superem a falta de ética, ajam com honestidade, integridade e transparência em todas as situações.',
]


GOD_WINS_FEEDBACK_TEXTS = [
    'Parabéns, aventureiros! Sua inteligência e trabalho em equipe foram cruciais para resolver este enigma desafiador.',
    'Admiro a persistência e criatividade que vocês demonstraram ao superar este puzzle.',
    'Vocês são um exemplo de bravura e engenhosidade para todos os aventureiros.',
    'Com suas habilidades e mentes afiadas, vocês conquistaram um feito que poucos alcançariam.',
    'Que sua vitória sirva de inspiração para que outros explorem o mundo com a mesma paixão e determinação.',
    'Parabéns por desvendar os segredos deste puzzle e desbloquear seus mistérios.',
    'Sua capacidade de resolver problemas e trabalhar juntos é realmente impressionante.',
    'Vocês mostraram que com união e inteligência, qualquer obstáculo pode ser superado.',
    'Aventureiros como vocês são a prova de que o heroísmo reside na mente e no coração.',
    'Que suas aventuras continuem a ser repletas de desafios e descobertas emocionantes.',
    'Sua vitória neste puzzle demonstra o poder da colaboração e do pensamento crítico.',
    'Com sua perspicácia e perspicácia, vocês desvendaram os segredos que este enigma guardava.',
    'Aventureiros como vocês são a inspiração para que todos busquem seus sonhos e objetivos.',
    'Que a chama da aventura nunca se apague em seus corações e que vocês continuem a explorar o desconhecido.',
    'Parabéns por mais uma conquista memorável! Sua jornada neste puzzle foi épica.',
    'Vocês são um verdadeiro exemplo de como a inteligência, a perseverança e o trabalho em equipe podem superar qualquer desafio.',
    'Que este puzzle seja apenas o começo de muitas outras aventuras incríveis em suas vidas.',
    'Continuem explorando, desvendando mistérios e conquistando novos desafios com a mesma bravura que demonstraram neste puzzle.',
    'Aventureiros como vocês são a prova de que não há limites para o que podemos alcançar quando nos unimos e utilizamos nossas habilidades.',
    'Que suas vitórias sirvam de inspiração para que todos acreditem em seus sonhos e busquem seus objetivos com determinação.',
    'Parabéns por mais um enigma solucionado! Sua mente afiada e sua capacidade de trabalhar em equipe foram essenciais para o sucesso.',
    'Aventureiros como vocês são a alma da exploração e da descoberta. Que sua paixão pela aventura continue a florescer.',
    'Que este puzzle seja apenas mais um passo em sua jornada épica pelo mundo.',
    'Continuem a desvendar mistérios, superar desafios e conquistar novos horizontes com a mesma determinação e inteligência.',
    'Aventureiros como vocês são a prova de que com coragem, inteligência e trabalho em equipe, qualquer obstáculo pode ser superado.',
    'Que suas vitórias sirvam de inspiração para que todos busquem seus sonhos e acreditem em seu potencial.',
    'Parabéns por desvendar os segredos deste puzzle e desbloquear seus mistérios! Vocês são verdadeiros mestres da aventura.',
    'Aventureiros como vocês são a inspiração para que todos explorem o mundo com a mesma paixão e entusiasmo.',
    'Que este puzzle seja apenas mais um capítulo em sua história de heroísmo e descobertas.',
    'Continuem a explorar, desvendar mistérios e conquistar novos desafios com a mesma bravura e inteligência que demonstraram neste puzzle.',
    'Incrível trabalho, aventureiros! Sua inteligência e trabalho em equipe foram cruciais para resolver o puzzle.',
    'Parabéns pela sua perspicácia e tenacidade! Vocês superaram todos os desafios com maestria.',
    'Que mentes brilhantes! Sua capacidade de solucionar problemas é digna de admiração.',
    'Vocês são verdadeiros mestres do puzzle! Sua habilidade e determinação são inspiradoras.',
    'Uau! Vocês desvendaram o puzzle com uma rapidez impressionante!',
    'Parabéns por essa conquista fantástica! Vocês demonstraram grande criatividade e estratégia.',
    'Seu trabalho em equipe foi impecável! Vocês se comunicaram e colaboraram de forma exemplar.',
    'Vocês não desistiram nem por um momento! Sua perseverança foi fundamental para o sucesso.',
    'Parabéns por essa vitória memorável! Vocês são verdadeiros aventureiros.',
    'Vocês nos mostraram que o trabalho em equipe e a inteligência podem superar qualquer obstáculo.',
    'Que aventura incrível! Vocês enfrentaram desafios e resolveram puzzles com maestria.',
    'Parabéns por essa demonstração de força e inteligência! Vocês são aventureiros excepcionais.',
    'Sua capacidade de pensar fora da caixa foi fundamental para desvendar o puzzle.',
    'Vocês são um exemplo de como a colaboração e a criatividade podem levar ao sucesso.',
    'Parabéns por essa conquista épica! Vocês marcaram seus nomes na história dos aventureiros.',
    'Sua vitória inspira a todos nós a buscarmos novos desafios e superarmos nossos limites.',
    'Vocês são a prova de que com determinação e trabalho em equipe, tudo é possível.',
    'Parabéns por essa aventura inesquecível! Vocês nos proporcionaram momentos de muita emoção.',
    'Que aventura épica! Vocês enfrentaram perigos e resolveram puzzles com bravura e inteligência.',
    'Parabéns por essa conquista memorável! Vocês são verdadeiros heróis.',
    'Sua vitória nos mostra que com persistência e inteligência, podemos alcançar qualquer objetivo.',
    'Vocês são um exemplo de como a bravura e a criatividade podem levar ao sucesso.',
    'Parabéns por essa aventura incrível! Vocês nos inspiraram a buscarmos novos desafios.',
    'Que aventura emocionante! Vocês nos prenderam do início ao fim com sua inteligência e bravura.',
    'Parabéns por essa conquista épica! Vocês são aventureiros excepcionais.',
    'Sua vitória nos mostra que com trabalho em equipe e determinação, podemos superar qualquer obstáculo.',
    'Vocês são um exemplo de como a colaboração e a criatividade podem levar ao sucesso.',
    'Parabéns por essa aventura inesquecível! Vocês marcaram seus nomes na história dos aventureiros.',
    'Sua vitória inspira a todos nós a buscarmos novos desafios e superarmos nossos limites.',
    'Vocês são a prova de que com persistência e inteligência, podemos alcançar qualquer objetivo.',
    'Parabéns, aventureiros! Sua inteligência e trabalho em equipe foram cruciais para resolver este enigma desafiador.',
    'Admiro a persistência e criatividade que vocês demonstraram ao superar este puzzle.',
    'Vocês são um exemplo de bravura e sagacidade, e merecem todos os elogios por sua vitória.',
    'Com mentes afiadas e corações corajosos, vocês conquistaram este desafio épico.',
    'Sua capacidade de pensar fora da caixa e colaborar uns com os outros foi fundamental para o sucesso.',
    'Parabéns por desvendar os segredos deste puzzle e provar que são verdadeiros aventureiros.',
    'A perseverança e a engenhosidade de vocês inspiraram a todos que acompanharam esta jornada.',
    'Vocês demonstraram que, com trabalho em equipe e determinação, qualquer obstáculo pode ser superado.',
    'A vitória de vocês neste puzzle é um marco que será lembrado por todos.',
    'Parabéns por se tornarem lendas! Sua conquista será contada por muitas gerações.',
    'Vocês são a prova viva de que a inteligência e a bravura podem superar qualquer desafio.',
    'Com suas mentes brilhantes e corações corajosos, vocês conquistaram o impossível.',
    'A vitória de vocês neste puzzle é um triunfo da mente humana sobre o mistério.',
    'Parabéns por se tornarem heróis! Vocês salvaram o dia e provaram que são incríveis.',
    'Sua conquista neste puzzle é um exemplo de como a união faz a força.',
    'Vocês são a inspiração para todos que sonham em realizar grandes feitos.',
    'Com inteligência, bravura e trabalho em equipe, vocês conquistaram a glória.',
    'Parabéns por se tornarem mestres dos puzzles! Vocês desvendaram o que muitos achavam impossível.',
    'A vitória de vocês neste puzzle é um presente para o mundo, pois abre caminho para novas descobertas.',
    'Vocês são a prova de que com determinação e perseverança, podemos alcançar qualquer coisa.',
    'Parabéns por se tornarem lendas! A história de suas aventuras será contada para sempre.',
    'Com suas mentes afiadas e corações corajosos, vocês conquistaram o impossível.',
    'A vitória de vocês neste puzzle é um triunfo da inteligência humana sobre o mistério.',
    'Parabéns por se tornarem heróis! Vocês salvaram o dia e provaram que são incríveis.',
    'Sua conquista neste puzzle é um exemplo de como a união faz a força.',
    'Vocês são a inspiração para todos que sonham em realizar grandes feitos.',
    'Com inteligência, bravura e trabalho em equipe, vocês conquistaram a glória.',
    'Parabéns por se tornarem mestres dos puzzles! Vocês desvendaram o que muitos achavam impossível.',
    'A vitória de vocês neste puzzle é um presente para o mundo, pois abre caminho para novas descobertas.',
    'Vocês são a prova de que com determinação e perseverança, podemos alcançar qualquer coisa.',
]


GODS_LOSES_FEEDBACK_TEXTS = [
    'Que seus mapas sempre levem vocês a becos sem saída e que seus compassos sempre apontem para o norte!',
    'Que a escuridão da caverna se torne sua companheira constante e que o eco dos seus passos seja o único som que vocês ouçam!',
    'Que a fome roa seus estômagos e a sede queime suas gargantas até que vocês encontrem o caminho que não conseguiram desvendar!',
    'Que o sono se torne um pesadelo eterno, assombrado pelos fantasmas dos desafios que vocês não superaram!',
    'Que a sorte os abandone para sempre e que a má sorte se torne sua sombra inseparável!',
    'Que a luz da lua se apague em sua presença e que as estrelas se escondam atrás das nuvens, deixando-os na escuridão da sua própria falha!',
    'Que a água se torne amarga e a comida sem sabor, lembrando-os constantemente do banquete que vocês não conquistaram!',
    'Que os animais da floresta se tornem seus inimigos, atacando-os sem piedade a cada passo que vocês derem!',
    'Que as plantas se entrelacem em seus caminhos, impedindo-os de avançar e forçando-os a revisitar seus erros!',
    'Que as ilusões os enganem e os desviem do caminho verdadeiro, levando-os cada vez mais longe da solução que vocês buscaram!',
    'Que a memória os traia e que vocês esqueçam os detalhes cruciais que os levarão ao sucesso!',
    'Que a dúvida corroa sua mente e que a incerteza os paralise, impedindo-os de tomar as decisões necessárias!',
    'Que o medo se torne seu guia e que a coragem os abandone quando vocês mais precisarem!',
    'Que a esperança se torne um fogo fraco que se apaga com cada vento contrário, deixando-os desamparados e sem direção!',
    'Que a frustração se torne sua companheira constante e que a raiva os consuma, impedindo-os de aprender com seus erros!',
    'Que a arrogância os cegue e que a humildade os abandone, impedindo-os de reconhecer a força que reside em seus companheiros!',
    'Que a desunião os divida e que a discórdia os enfraqueça, tornando-os incapazes de superar os desafios que os esperam!',
    'Que a inveja os consuma e que a ganância os corrompa, levando-os a tomar decisões precipitadas e desastrosas!',
    'Que a traição os assombre e que a confiança se torne um bem raro e precioso que vocês nunca mais encontrarão!',
    'Que a morte os ronde a cada passo e que o fantasma do fracasso os persiga para sempre, servindo como um lembrete constante da sua falha!',
    'Que seus nomes sejam esquecidos e que suas histórias se percam no tempo, como se vocês nunca tivessem existido!',
    'Que seus feitos sejam ridicularizados e que suas conquistas sejam diminuídas, deixando-os sem reconhecimento e sem honra!',
    'Que seus sonhos se transformem em pesadelos e que suas ambições se tornem cinzas, deixando-os vazios e sem esperança!',
    'Que seus corações se tornem pedras e que suas almas se tornem frias, incapazes de sentir alegria ou satisfação jamais!',
    'Que a loucura os consuma e que a sanidade os abandone, deixando-os presos em um mundo de ilusões e tormentos!',
    'Que a maldição deste puzzle os acompanhe para sempre, assombrando cada passo que vocês derem e cada decisão que tomarem!',
    'Que a sombra do fracasso se projete sobre vocês, impedindo-os de ver a luz do sucesso que poderia ser seu!',
    'Que a culpa os consuma e que o arrependimento os corroa, fazendo-os questionar cada escolha que fizeram!',
    'Que a vergonha os domine e que o orgulho os abandone, deixando-os humilhados e incapazes de levantar a cabeça!',
    'Que a maldição deste puzzle seja um lembrete constante da sua falha, para que vocês nunca mais se atreveram a desafiar o desconhecido sem a devida preparação e determinação!',
    'Que a areia do tempo se torne lama em seus pés, atrasando cada passo em sua jornada.',
    'Que a luz da lua se torne escuridão eterna, cegando seus olhos para o caminho.',
    'Que a fome arda em seus estômagos como chamas, consumindo-os por dentro.',
    'Que a sede queime suas gargantas como brasas, secando a vida de seus corpos.',
    'Que o sono se torne pesadelo, assombrando-os com visões de sua própria falha.',
    'Que a ilusão se torne realidade, distorcendo seus sentidos e levando-os à loucura.',
    'Que o medo se torne seu companheiro, paralisando-os diante de cada desafio.',
    'Que a dúvida se torne sua guia, desviando-os do caminho verdadeiro.',
    'Que a fraqueza se torne sua força, tornando-os vulneráveis aos seus inimigos.',
    'Que a traição se torne sua aliada, derrubando-os quando menos esperarem.',
    'Que a maldição dos ancestrais recaia sobre vocês, condenando-os à eterna desventura.',
    'Que os espíritos da floresta os persigam, sussurrando palavras de desespero em seus ouvidos.',
    'Que as criaturas das sombras os assombrem, atacando-os na noite sem lua.',
    'Que a tempestade eterna os açoite, inundando seus caminhos e afogando seus sonhos.',
    'Que o fogo do vulcão os consuma, reduzindo-os a cinzas e esquecimento.',
    'Que o gelo da tundra os congele, aprisionando-os em um túmulo de gelo eterno.',
    'Que a maldição do deserto os persiga, condenando-os a vagar sem água ou descanso.',
    'Que a peste os consuma, corroendo seus corpos e levando-os à morte dolorosa.',
    'Que a loucura os domine, distorcendo seus pensamentos e levando-os à destruição.',
    'Que a maldição da ganância os corrompa, cegando-os para a verdadeira riqueza da vida.',
    'Que a maldição do orgulho os derrube, fazendo-os cair em desgraça e humilhação.',
    'Que a maldição da inveja os consuma, corroendo seus corações e transformando-os em amargura.',
    'Que a maldição da ira os domine, levando-os à violência e à autodestruição.',
    'Que a maldição do preconceito os cegue, impedindo-os de ver a verdade e a justiça.',
    'Que a maldição da apatia os consuma, tornando-os indiferentes ao sofrimento dos outros.',
    'Que a maldição da covardia os paralise, impedindo-os de enfrentar seus medos e desafios.',
    'Que a maldição da mentira os condene, tornando-os incapazes de serem confiáveis ou respeitados.',
    'Que a maldição da crueldade os endureça, tornando-os incapazes de sentir compaixão ou empatia.',
    'Que a maldição da traição os assombre, fazendo-os perder a fé na amizade e no amor.',
    'Que a maldição da morte os consuma, levando-os à escuridão eterna e ao esquecimento.',
    'Que a luz do sol se torne cegante para vocês, impedindo-os de navegar por qualquer terra ou mar.',
    'Que seus mapas se tornem inúteis, guiando-os apenas para perigos e armadilhas.',
    'Que seus compassos girem loucamente, levando-os em círculos sem fim.',
    'Que seus alimentos se tornem repugnantes, com sabor de terra e cinzas.',
    'Que sua água se torne amarga e insípida, incapaz de matar a sede.',
    'Que seus sonhos se tornem pesadelos vívidos, assombrados por monstros e horrores.',
    'Que seus segredos mais íntimos sejam revelados para todos que encontrarem.',
    'Que suas habilidades se tornem inúteis, falhando em qualquer tarefa que tentarem realizar.',
    'Que seus amigos se tornem inimigos, traindo-os na primeira oportunidade.',
    'Que seus inimigos se tornem invencíveis, incapazes de serem derrotados por qualquer meio.',
    'Que a chuva caia incessantemente sobre vocês, transformando o caminho em lama e pântano.',
    'Que o calor do sol se torne abrasador, queimando sua pele e desidratando seus corpos.',
    'Que o frio da noite se torne penetrante, congelando seus ossos e roubando seu calor.',
    'Que os animais selvagens se tornem hostis, atacando-os sem provocação.',
    'Que as plantas se tornem venenosas, liberando toxinas perigosas com o menor toque.',
    'Que os terrenos se tornem instáveis, desmoronando sob seus pés e os jogando em abismos.',
    'Que as ilusões os enganem, levando-os por caminhos falsos e perigosos.',
    'Que a paranóia os consuma, fazendo-os duvidar de cada sombra e sussurro.',
    'Que o medo se apodere de seus corações, paralisando-os diante do menor perigo.',
    'Que a esperança se extinga em suas almas, deixando apenas desespero e desamparo.',
    'Que seus nomes sejam esquecidos, apagados da história e da memória.',
    'Que seus feitos sejam esvaziados, sem valor ou significado para ninguém.',
    'Que seus sacrifícios sejam em vão, sem recompensa ou reconhecimento.',
    'Que seus legados sejam corrompidos, transformados em algo grotesco e maligno.',
    'Que suas almas sejam amaldiçoadas, condenadas a vagar eternamente como fantasmas inquietos.',
    'Que seus corpos sejam amaldiçoados, apodrecendo e se deteriorando enquanto ainda vivem.',
    'Que suas mentes sejam amaldiçoadas, atormentadas por insanidade e loucura.',
    'Que seus corações sejam amaldiçoados, incapazes de sentir amor, alegria ou compaixão.',
    'Que seus espíritos sejam amaldiçoados, corrompidos pela escuridão e pelo mal.',
    'Que a maldição dos aventureiros falhos recaia sobre todos que os conhecerem, espalhando desespero e desgraça por onde passarem.',
]


GODS_TIMEOUT_FEEDBACK_TEXTS = [
    'O tempo se esgotou! A maldição ancestral se aproxima, aventureiros!',
    'A ampulheta se esvaziou. Preparem-se para enfrentar a maldição que assola este lugar!',
    'A sombra da maldição se aproxima! Apressem-se, bravos aventureiros, o tempo se esvai!',
    'O portal se fechará em instantes! A maldição será libertada se não alcançarmos nosso objetivo!',
    'Cuidado, aventureiros! Os sinos da maldição soam! Corram contra o tempo!',
    'O labirinto se fecha! A névoa da maldição os consumirá se não encontrarem a saída!',
    'A lua de sangue surge no céu! A maldição se intensifica! Aventureiros, o tempo é agora!',
    'O rugido do monstro ecoa! A maldição toma forma! Aventureiros, lutem com bravura!',
    'As runas se apagam! A maldição está prestes a ser libertada! Aventureiros, decifrem o enigma!',
    'O elixir se esgota! A maldição se espalhará! Aventureiros, bebam antes que seja tarde!',
    'O portal se abre! A maldição os espera do outro lado! Aventureiros, entrem com coragem!',
    'O sacrifício deve ser feito! A maldição exige um preço! Aventureiros, escolham com sabedoria!',
    'A profecia se cumpre! A maldição se manifesta! Aventureiros, enfrentem seu destino!',
    'O enigma final se revela! A maldição tem uma chave! Aventureiros, desvendem o segredo!',
    'O tempo se distorce! A maldição distorce a realidade! Aventureiros, confiem em seus instintos!',
    'A escuridão toma conta! A maldição cega seus olhos! Aventureiros, usem a luz da esperança!',
    'O silêncio reina! A maldição silencia seus gritos! Aventureiros, usem a força da união!',
    'O chão treme! A maldição sacode o mundo! Aventureiros, permaneçam firmes!',
    'O ar se torna tóxico! A maldição envenena seus pulmões! Aventureiros, encontrem refúgio!',
    'A morte se aproxima! A maldição os consome! Aventureiros, lutem pela vida!',
    'A esperança se esvai! A maldição os desanima! Aventureiros, acreditem em si mesmos!',
    'O amor se transforma em ódio! A maldição corrompe seus corações! Aventureiros, mantenham a compaixão!',
    'A fé se torna dúvida! A maldição questiona suas crenças! Aventureiros, encontrem a verdade!',
    'A sanidade se esvai! A maldição distorce suas mentes! Aventureiros, mantenham o foco!',
    'O tempo se repete! A maldição os prende em um ciclo! Aventureiros, quebrem a corrente!',
    'O passado retorna! A maldição os confronta com seus erros! Aventureiros, aprendam com o passado!',
    'O futuro se desfaz! A maldição rouba seus sonhos! Aventureiros, reescrevam o futuro!',
    'A maldição é poderosa! Aventureiros, unam suas forças!',
    'A maldição é traiçoeira! Aventureiros, estejam vigilantes!',
    'A maldição é implacável! Aventureiros, sejam implacáveis em sua luta!',
]
