WORD_GOD_NAME = 'Hermes'
SECTION_TEXT_WORDGAME = 'DESAFIO'


WORD_START_NARRATION_TEXTS = [
    'WORD_START_NARRATION_TEXTS EM DESENVOLVIMENTO.'
]


WORD_GOD_GREETINGS_TEXTS = [
    'WORD_GOD_GREETINGS_TEXTS EM DESENVOLVIMENTO.'
]


WORD_GOD_TIMEOUT_FEEDBACK_TEXTS = [
    'WORD_GOD_TIMEOUT_FEEDBACK_TEXTS EM DESENVOLVIMENTO.'
]

WORD_GOD_LOSES_FEEDBACK_TEXTS = [
    'WORD_GOD_LOSES_FEEDBACK_TEXTS EM DESENVOLVIMENTO.'
]