from rpgram.enums import EmojiEnum

PLAYER_FULL = 'Jogador'
CHARACTER_FULL = 'Personagem'
RACE_FULL = 'Raça'
CLASS_FULL = 'Classe'

LEVEL_ABB = 'NV'
LEVEL_FULL = 'Nível'
LEVEL_CLASS_FULL = 'Nível da Classe'
XP_ABB = 'XP'
XP_FULL = 'Experiência'
ATTRIBUTE_POINTS_ABB = 'AP'
ATTRIBUTE_POINTS_FULL = 'Pontos'

STRENGTH_ABB = 'FOR'
DEXTERITY_ABB = 'DES'
CONSTITUTION_ABB = 'CON'
INTELLIGENCE_ABB = 'INT'
WISDOM_ABB = 'SAB'
CHARISMA_ABB = 'CAR'

HIT_POINT_ABB = 'HP'
INITIATIVE_FULL = 'INICIATIVA'
PHYSICAL_ATTACK_FULL = 'ATAQUE FÍSICO'
PRECISION_ATTACK_FULL = 'ATAQUE DE PRECISÃO'
MAGICAL_ATTACK_FULL = 'ATAQUE MÁGICO'
PHYSICAL_DEFENSE_FULL = 'DEFESA FÍSICA'
MAGICAL_DEFENSE_FULL = 'DEFESA MÁGICA'
HIT_FULL = 'ACERTO'
EVASION_FULL = 'EVASÃO'

PLAYER_EMOJI_TEXT = f'{EmojiEnum.PLAYER.value}{PLAYER_FULL}'
CHARACTER_EMOJI_TEXT = f'{EmojiEnum.CHARACTER.value}{CHARACTER_FULL}'
RACE_EMOJI_TEXT = f'{EmojiEnum.RACE.value}{RACE_FULL}'
CLASS_EMOJI_TEXT = f'{EmojiEnum.CLASS.value}{CLASS_FULL}'
LEVEL_EMOJI_TEXT = f'{EmojiEnum.LEVEL.value}{LEVEL_FULL}'
LEVEL_CLASS_EMOJI_TEXT = f'{EmojiEnum.LEVEL_CLASS.value}{LEVEL_CLASS_FULL}'
XP_EMOJI_TEXT = f'{EmojiEnum.XP.value}{XP_FULL}'
ATTRIBUTE_POINTS_EMOJI_TEXT = (
    f'{EmojiEnum.ATTRIBUTE_POINTS.value}{ATTRIBUTE_POINTS_FULL}'
)

STRENGTH_EMOJI_TEXT = f'{EmojiEnum.STRENGTH.value}{STRENGTH_ABB}'
DEXTERITY_EMOJI_TEXT = f'{EmojiEnum.DEXTERITY.value}{DEXTERITY_ABB}'
CONSTITUTION_EMOJI_TEXT = f'{EmojiEnum.CONSTITUTION.value}{CONSTITUTION_ABB}'
INTELLIGENCE_EMOJI_TEXT = f'{EmojiEnum.INTELLIGENCE.value}{INTELLIGENCE_ABB}'
WISDOM_EMOJI_TEXT = f'{EmojiEnum.WISDOM.value}{WISDOM_ABB}'
CHARISMA_EMOJI_TEXT = f'{EmojiEnum.CHARISMA.value}{CHARISMA_ABB}'

HIT_POINT_EMOJI_TEXT = f'{EmojiEnum.HIT_POINT.value}{HIT_POINT_ABB}'
INITIATIVE_EMOJI_TEXT = f'{EmojiEnum.INITIATIVE.value}{INITIATIVE_FULL}'
PHYSICAL_ATTACK_EMOJI_TEXT = (
    f'{EmojiEnum.PHYSICAL_ATTACK.value}{PHYSICAL_ATTACK_FULL}'
)
PRECISION_ATTACK_EMOJI_TEXT = (
    f'{EmojiEnum.PRECISION_ATTACK.value}{PRECISION_ATTACK_FULL}'
)
MAGICAL_ATTACK_EMOJI_TEXT = (
    f'{EmojiEnum.MAGICAL_ATTACK.value}{MAGICAL_ATTACK_FULL}'
)
PHYSICAL_DEFENSE_EMOJI_TEXT = (
    f'{EmojiEnum.PHYSICAL_DEFENSE.value}{PHYSICAL_DEFENSE_FULL}'
)
MAGICAL_DEFENSE_EMOJI_TEXT = (
    f'{EmojiEnum.MAGICAL_DEFENSE.value}{MAGICAL_DEFENSE_FULL}'
)
HIT_EMOJI_TEXT = f'{EmojiEnum.HIT.value}{HIT_FULL}'
EVASION_EMOJI_TEXT = f'{EmojiEnum.EVASION.value}{EVASION_FULL}'
