from enum import Enum


class ClasseEnum(Enum):
    BARBARIAN = 'Bárbaro'
    CLERIC = 'Clérigo'
    DRUID = 'Druida'
    SORCERER = 'Feiticeiro'
    WARRIOR = 'Guerreiro'
    ROGUE = 'Ladino'
    MAGE = 'Mago'
    PALADIN = 'Paladino'
    GUARDIAN = 'Guardião'
    DUELIST = 'Duelista'
    HERALD = 'Arauto'
    ARCANIST = 'Arcanista'
    BARD = 'Bardo'
    BOUNTY_HUNTER = 'Caçador de Recompensas'
    KNIGHT = 'Cavaleiro'
    HEALER = 'Curandeiro'
    GLADIATOR = 'Gladiador'
    SUMMONER = 'Invocador'
    MERCENARY = 'Mercenário'
    NECROMANCER = 'Necromante'
    RANGER = 'Patrulheiro'
    SHAMAN = 'Xamã'
    BERSERKIR = 'Berserkir'
    WEAPON_MASTER = 'Mestre das Armas'
    SORCERER_SUPREME = 'Feiticeiro Supremo'
    LORD_OF_THE_ROGUES = 'Senhor dos Ladinos'
    SAMURAI = 'Samurai'
