from enum import Enum


class EmojiEnum(Enum):
    BACK = '↪️'
    CLOSE_BAG = '🎒'
    DEAD = '☠️'
    DEFEND = '🛡'
    DICE = '🎲'
    DODGE = '🥾'
    EQUIPMENT_POWER = '🔸'
    HEALING = '💞'
    HIT = '🎯'
    EVASION = '🥾'
    MAGICAL_ATTACK = '✨'
    MAGICAL_DEFENSE = '🔮'
    PHYSICAL_ATTACK = '💥'
    PHYSICAL_DEFENSE = '🛡'
    PRECISION_ATTACK = '💫'
    PRECISION_DEFENSE = '🛡'
    PAGE = '📜'
    TEAM_BLUE = '🔵'
    TEAM_RED = '🔴'
    TEAM_WHITE = '🔘'
    TO_EQUIP = '🗡️'
    USE_POTION = '🧪'
    PREVIOUS = '⬅'
    NEXT = '➡'
    UP = '📈'
    DOWN = '📉'
    WEIGHT = '⚖'
    LEFT = '👈'
    RIGHT = '👉'
