from typing import Union

from rpgram.enums.classe import ClasseEnum


def factory_skill_factory(classe_name: Union[ClasseEnum, str]):
    '''Retorna uma função factory relacionada ao classe_name
    '''

    if isinstance(classe_name, ClasseEnum):
        classe_name = classe_name.value

    if ClasseEnum.BARBARIAN.value == classe_name:
        ...
    elif ClasseEnum.CLERIC.value == classe_name:
        ...
    elif ClasseEnum.DRUID.value == classe_name:
        ...
    elif ClasseEnum.SORCERER.value == classe_name:
        ...
    elif ClasseEnum.WARRIOR.value == classe_name:
        ...
    elif ClasseEnum.ROGUE.value == classe_name:
        ...
    elif ClasseEnum.MAGE.value == classe_name:
        ...
    elif ClasseEnum.PALADIN.value == classe_name:
        ...
    elif ClasseEnum.GUARDIAN.value == classe_name:
        ...
    elif ClasseEnum.DUELIST.value == classe_name:
        ...
    elif ClasseEnum.HERALD.value == classe_name:
        ...
    elif ClasseEnum.ARCANIST.value == classe_name:
        ...
    elif ClasseEnum.BARD.value == classe_name:
        ...
    elif ClasseEnum.BOUNTY_HUNTER.value == classe_name:
        ...
    elif ClasseEnum.KNIGHT.value == classe_name:
        ...
    elif ClasseEnum.HEALER.value == classe_name:
        ...
    elif ClasseEnum.GLADIATOR.value == classe_name:
        ...
    elif ClasseEnum.SUMMONER.value == classe_name:
        ...
    elif ClasseEnum.MERCENARY.value == classe_name:
        ...
    elif ClasseEnum.NECROMANCER.value == classe_name:
        ...
    elif ClasseEnum.RANGER.value == classe_name:
        ...
    elif ClasseEnum.SHAMAN.value == classe_name:
        ...
    elif ClasseEnum.SAMURAI.value == classe_name:
        ...
    elif ClasseEnum.BERSERKIR.value == classe_name:
        ...
    elif ClasseEnum.WEAPON_MASTER.value == classe_name:
        ...
    elif ClasseEnum.SORCERER_SUPREME.value == classe_name:
        ...
    elif ClasseEnum.LORD_OF_THE_ROGUES.value == classe_name:
        ...
