from bot.conversation.sign_up_player import SIGNUP_PLAYER_HANDLER
from bot.conversation.sign_up_group import SIGNUP_GROUP_HANDLER
from bot.conversation.create_char import CREATE_CHAR_HANDLER
from bot.conversation.help import HELP_HANDLER